/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/iv1AOPpuE3Q
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

export function Lobby() {
  return (
    <>
      <h1 className="text-3xl font-bold text-center mb-4">Room</h1>
      <p className="text-sm text-center text-gray-500 dark:text-gray-400">This is a room</p>
      <div className="grid gap-4 w-full max-w-sm sm:max-w-none">
        <div className="flex items-center space-x-4">
          <Avatar className="w-10 h-10 border-2 border-white">
            <AvatarImage alt="@jaredpalmer" src="/placeholder-user.jpg" />
            <AvatarFallback>JP</AvatarFallback>
          </Avatar>
          <div className="space-y-1.5">
            <h3 className="text-sm font-bold tracking-wide">Jared Palmer</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">Frontend Engineer</p>
          </div>
        </div>
        <div className="flex items-center space-x-4">
          <Avatar className="w-10 h-10 border-2 border-white">
            <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
            <AvatarFallback>CN</AvatarFallback>
          </Avatar>
          <div className="space-y-1.5">
            <h3 className="text-sm font-bold tracking-wide">shadcn</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">Expert UI library</p>
          </div>
        </div>
        <div className="flex items-center space-x-4">
          <Avatar className="w-10 h-10 border-2 border-white">
            <AvatarImage alt="@maxleiter" src="/placeholder-user.jpg" />
            <AvatarFallback>ML</AvatarFallback>
          </Avatar>
          <div className="space-y-1.5">
            <h3 className="text-sm font-bold tracking-wide">Max Leiter</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">OpenAI Engineer</p>
          </div>
        </div>
        <div className="flex items-center space-x-4">
          <Avatar className="w-10 h-10 border-2 border-white">
            <AvatarImage alt="@shuding_" src="/placeholder-user.jpg" />
            <AvatarFallback>SD</AvatarFallback>
          </Avatar>
          <div className="space-y-1.5">
            <h3 className="text-sm font-bold tracking-wide">Shu Ding</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">Vercel Designer</p>
          </div>
        </div>
      </div>
      <Button className="w-full max-w-sm mx-auto mt-8">Leave Room</Button>
    </>
  )
}
