/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MrXILtfBawD
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Main() {
  return (
    <div className="flex items-center justify-center h-screen">
      <Card className="w-full max-w-lg">
        <CardHeader>
          <CardTitle className="text-lg">Game Room Lobby</CardTitle>
          <CardDescription>Enter the room code to join the game.</CardDescription>
        </CardHeader>
        <CardContent className="flex items-start gap-4 pt-4">
          <div className="grid w-full gap-2">
            <Label htmlFor="name">Your Name</Label>
            <Input id="name" placeholder="Name" />
          </div>
          <div className="grid w-full gap-2">
            <Label htmlFor="room-code">Room Code</Label>
            <Input id="room-code" placeholder="Room Code" />
          </div>
        </CardContent>
        <CardFooter className="flex">
          <Button className="mr-2">Create Room</Button>
          <Button className="ml-auto">Join Room</Button>
        </CardFooter>
      </Card>
    </div>
  )
}
